/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Артем' at '08.12.17 18:36' with Gradle 2.14.1
 *
 * @author Артем, @date 08.12.17 18:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
